import { ITEM_CATEGORY } from "./items";

export const EQUIPMENT = Object.freeze({
  EXCAVATION_RIG: "Excavation Rig",
  FEDERATION_EXO_BOOTS: "Federation Exo Boots",
  FEDERATION_EXO_HELMET: "Federation Exo Helmet",
  FEDERATION_EXO_CHESTPIECE: "Federation Exo-Chestpiece",
  FEDERATION_EXO_GLOVES: "Federation Exo-Gloves",
  FEDERATION_EXO_LEGGINGS: "Federation Exo-leggings",
  HANDCUFFS: "Handcuffs",
  PHASE_CANNON_RIG: "Phase Cannon Rig",
  CHITIN_BOOTS: "Chitin Boots",
  CHITIN_CHESTPIECE: "Chitin Chestpiece",
  CHITIN_GAUNTLETS: "Chitin Gauntlets",
  CHITIN_HELMET: "Chitin Helmet",
  CHITIN_LEGGINGS: "Chitin Leggings",
  CLOTH_BOOTS: "Cloth Boots",
  CLOTH_GLOVES: "Cloth Gloves",
  CLOTH_HAT: "Cloth Hat",
  CLOTH_PANTS: "Cloth Pants",
  CLOTH_SHIRT: "Cloth Shirt",
  DESERT_CLOTH_BOOTS: "Desert Cloth Boots",
  DESERT_CLOTH_GLOVES: "Desert Cloth Gloves",
  DESERT_CLOTH_PANTS: "Desert Cloth Pants",
  DESERT_CLOTH_SHIRT: "Desert Cloth Shirt",
  DESERT_GOGGLES_AND_HAT: "Desert Goggles and Hat",
  FLAK_BOOTS: "Flak Boots",
  FLAK_CHESTPIECE: "Flak Chestpiece",
  FLAK_GAUNTLETS: "Flak Gauntlets",
  FLAK_HELMET: "Flak Helmet",
  FLAK_LEGGINGS: "Flak Leggings",
  FUR_BOOTS: "Fur Boots",
  FUR_CAP: "Fur Cap",
  FUR_CHESTPIECE: "Fur Chestpiece",
  FUR_GAUNTLETS: "Fur Gauntlets",
  FUR_LEGGINGS: "Fur Leggings",
  GAS_MASK: "Gas Mask",
  GHILLIE_BOOTS: "Ghillie Boots",
  GHILLIE_CHESTPIECE: "Ghillie Chestpiece",
  GHILLIE_GAUNTLETS: "Ghillie Gauntlets",
  GHILLIE_LEGGINGS: "Ghillie Leggings",
  GHILLIE_MASK: "Ghillie Mask",
  HAZARD_SUIT_BOOTS: "Hazard Suit Boots",
  HAZARD_SUIT_GLOVES: "Hazard Suit Gloves",
  HAZARD_SUIT_HAT: "Hazard Suit Hat",
  HAZARD_SUIT_PANTS: "Hazard Suit Pants",
  HAZARD_SUIT_SHIRT: "Hazard Suit Shirt",
  HEAVY_MINERS_HELMET: "Heavy Miner's Helmet",
  HIDE_BOOTS: "Hide Boots",
  HIDE_GLOVES: "Hide Gloves",
  HIDE_HAT: "Hide Hat",
  HIDE_PANTS: "Hide Pants",
  HIDE_SHIRT: "Hide Shirt",
  HYAENODON_MEATPACK: "Hyaenodon Meatpack",
  MDSM: "M.D.S.M.",
  MOMI: "M.O.M.I.",
  MRLM: "M.R.L.M.",
  MSCM: "M.S.C.M.",
  METAL_SHIELD: "Metal Shield",
  NATURAL_ARMOR: "Natural Armor",
  NIGHT_VISION_GOGGLES: "Night Vision Goggles",
  PLATFORM_CART: "Platform Cart",
  RIOT_BOOTS: "Riot Boots",
  RIOT_CHESTPIECE: "Riot Chestpiece",
  RIOT_GAUNTLETS: "Riot Gauntlets",
  RIOT_HELMET: "Riot Helmet",
  RIOT_LEGGINGS: "Riot Leggings",
  RIOT_SHIELD: "Riot Shield",
  SCUBA_FLIPPERS: "SCUBA Flippers",
  SCUBA_LEGGINGS: "SCUBA Leggings",
  SCUBA_MASK: "SCUBA Mask",
  SCUBA_TANK: "SCUBA Tank",
  WOODEN_SHIELD: "Wooden Shield",
  PULSE_CANNON_RIG: "Pulse Cannon Rig",
  RADAR_RIG: "Radar Rig",
  RESOURCE_ATTRACTOR_RIG: "Resource Attractor Rig",
  SHIELD_GENERATOR_RIG: "Shield Generator Rig",
  SHIELD_PROJECTOR_RIG: "Shield Projector Rig",
  SILENCE_CANNON_RIG: "Silence Cannon Rig",
  STRYDER_RIDING_PLATFORM: "Stryder Riding Platform",
  TEK_BOOTS: "Tek Boots",
  TEK_CHESTPIECE: "Tek Chestpiece",
  TEK_GAUNTLETS: "Tek Gauntlets",
  TEK_HELMET: "Tek Helmet",
  TEK_LEGGINGS: "Tek Leggings",
  TEK_SHIELD: "Tek Shield",
});

export const CATEGORISED_EQUIPMENT = Object.freeze([
  {
    name: EQUIPMENT.EXCAVATION_RIG,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Excavation Rig",
  },
  {
    name: EQUIPMENT.FEDERATION_EXO_BOOTS,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Federation Exo Boots",
  },
  {
    name: EQUIPMENT.FEDERATION_EXO_HELMET,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Federation Exo Helmet",
  },
  {
    name: EQUIPMENT.FEDERATION_EXO_CHESTPIECE,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Federation Exo-Chestpiece",
  },
  {
    name: EQUIPMENT.FEDERATION_EXO_GLOVES,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Federation Exo-Gloves",
  },
  {
    name: EQUIPMENT.FEDERATION_EXO_LEGGINGS,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Federation Exo-leggings",
  },
  {
    name: EQUIPMENT.HANDCUFFS,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Handcuffs",
  },
  {
    name: EQUIPMENT.PHASE_CANNON_RIG,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Phase Cannon Rig",
  },
  {
    name: EQUIPMENT.CHITIN_BOOTS,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Chitin Boots",
  },
  {
    name: EQUIPMENT.CHITIN_CHESTPIECE,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Chitin Chestpiece",
  },
  {
    name: EQUIPMENT.CHITIN_GAUNTLETS,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Chitin Gauntlets",
  },
  {
    name: EQUIPMENT.CHITIN_HELMET,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Chitin Helmet",
  },
  {
    name: EQUIPMENT.CHITIN_LEGGINGS,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Chitin Leggings",
  },
  {
    name: EQUIPMENT.CLOTH_BOOTS,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Cloth Boots",
  },
  {
    name: EQUIPMENT.CLOTH_GLOVES,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Cloth Gloves",
  },
  {
    name: EQUIPMENT.CLOTH_HAT,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Cloth Hat",
  },
  {
    name: EQUIPMENT.CLOTH_PANTS,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Cloth Pants",
  },
  {
    name: EQUIPMENT.CLOTH_SHIRT,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Cloth Shirt",
  },
  {
    name: EQUIPMENT.DESERT_CLOTH_BOOTS,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Desert Cloth Boots",
  },
  {
    name: EQUIPMENT.DESERT_CLOTH_GLOVES,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Desert Cloth Gloves",
  },
  {
    name: EQUIPMENT.DESERT_CLOTH_PANTS,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Desert Cloth Pants",
  },
  {
    name: EQUIPMENT.DESERT_CLOTH_SHIRT,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Desert Cloth Shirt",
  },
  {
    name: EQUIPMENT.DESERT_GOGGLES_AND_HAT,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Desert Goggles and Hat",
  },
  {
    name: EQUIPMENT.FLAK_BOOTS,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Flak Boots",
  },
  {
    name: EQUIPMENT.FLAK_CHESTPIECE,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Flak Chestpiece",
  },
  {
    name: EQUIPMENT.FLAK_GAUNTLETS,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Flak Gauntlets",
  },
  {
    name: EQUIPMENT.FLAK_HELMET,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Flak Helmet",
  },
  {
    name: EQUIPMENT.FLAK_LEGGINGS,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Flak Leggings",
  },
  {
    name: EQUIPMENT.FUR_BOOTS,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Fur Boots",
  },
  {
    name: EQUIPMENT.FUR_CAP,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Fur Cap",
  },
  {
    name: EQUIPMENT.FUR_CHESTPIECE,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Fur Chestpiece",
  },
  {
    name: EQUIPMENT.FUR_GAUNTLETS,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Fur Gauntlets",
  },
  {
    name: EQUIPMENT.FUR_LEGGINGS,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Fur Leggings",
  },
  {
    name: EQUIPMENT.GAS_MASK,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Gas Mask",
  },
  {
    name: EQUIPMENT.GHILLIE_BOOTS,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Ghillie Boots",
  },
  {
    name: EQUIPMENT.GHILLIE_CHESTPIECE,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Ghillie Chestpiece",
  },
  {
    name: EQUIPMENT.GHILLIE_GAUNTLETS,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Ghillie Gauntlets",
  },
  {
    name: EQUIPMENT.GHILLIE_LEGGINGS,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Ghillie Leggings",
  },
  {
    name: EQUIPMENT.GHILLIE_MASK,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Ghillie Mask",
  },
  {
    name: EQUIPMENT.HAZARD_SUIT_BOOTS,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Hazard Suit Boots",
  },
  {
    name: EQUIPMENT.HAZARD_SUIT_GLOVES,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Hazard Suit Gloves",
  },
  {
    name: EQUIPMENT.HAZARD_SUIT_HAT,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Hazard Suit Hat",
  },
  {
    name: EQUIPMENT.HAZARD_SUIT_PANTS,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Hazard Suit Pants",
  },
  {
    name: EQUIPMENT.HAZARD_SUIT_SHIRT,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Hazard Suit Shirt",
  },
  {
    name: EQUIPMENT.HEAVY_MINERS_HELMET,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Heavy Miner's Helmet",
  },
  {
    name: EQUIPMENT.HIDE_BOOTS,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Hide Boots",
  },
  {
    name: EQUIPMENT.HIDE_GLOVES,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Hide Gloves",
  },
  {
    name: EQUIPMENT.HIDE_HAT,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Hide Hat",
  },
  {
    name: EQUIPMENT.HIDE_PANTS,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Hide Pants",
  },
  {
    name: EQUIPMENT.HIDE_SHIRT,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Hide Shirt",
  },
  {
    name: EQUIPMENT.HYAENODON_MEATPACK,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Hyaenodon Meatpack",
  },
  {
    name: EQUIPMENT.MDSM,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "M.D.S.M.",
  },
  {
    name: EQUIPMENT.MOMI,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "M.O.M.I.",
  },
  {
    name: EQUIPMENT.MRLM,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "M.R.L.M.",
  },
  {
    name: EQUIPMENT.MSCM,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "M.S.C.M.",
  },
  {
    name: EQUIPMENT.METAL_SHIELD,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Metal Shield",
  },
  {
    name: EQUIPMENT.NATURAL_ARMOR,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Natural Armor",
  },
  {
    name: EQUIPMENT.NIGHT_VISION_GOGGLES,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Night Vision Goggles",
  },
  {
    name: EQUIPMENT.PLATFORM_CART,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Platform Cart",
  },
  {
    name: EQUIPMENT.RIOT_BOOTS,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Riot Boots",
  },
  {
    name: EQUIPMENT.RIOT_CHESTPIECE,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Riot Chestpiece",
  },
  {
    name: EQUIPMENT.RIOT_GAUNTLETS,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Riot Gauntlets",
  },
  {
    name: EQUIPMENT.RIOT_HELMET,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Riot Helmet",
  },
  {
    name: EQUIPMENT.RIOT_LEGGINGS,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Riot Leggings",
  },
  {
    name: EQUIPMENT.RIOT_SHIELD,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Riot Shield",
  },
  {
    name: EQUIPMENT.SCUBA_FLIPPERS,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "SCUBA Flippers",
  },
  {
    name: EQUIPMENT.SCUBA_LEGGINGS,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "SCUBA Leggings",
  },
  {
    name: EQUIPMENT.SCUBA_MASK,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "SCUBA Mask",
  },
  {
    name: EQUIPMENT.SCUBA_TANK,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "SCUBA Tank",
  },
  {
    name: EQUIPMENT.WOODEN_SHIELD,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Wooden Shield",
  },
  {
    name: EQUIPMENT.PULSE_CANNON_RIG,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Pulse Cannon Rig",
  },
  {
    name: EQUIPMENT.RADAR_RIG,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Radar Rig",
  },
  {
    name: EQUIPMENT.RESOURCE_ATTRACTOR_RIG,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Resource Attractor Rig",
  },
  {
    name: EQUIPMENT.SHIELD_GENERATOR_RIG,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Shield Generator Rig",
  },
  {
    name: EQUIPMENT.SHIELD_PROJECTOR_RIG,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Shield Projector Rig",
  },
  {
    name: EQUIPMENT.SILENCE_CANNON_RIG,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Silence Cannon Rig",
  },
  {
    name: EQUIPMENT.STRYDER_RIDING_PLATFORM,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Stryder Riding Platform",
  },
  {
    name: EQUIPMENT.TEK_BOOTS,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Tek Boots",
  },
  {
    name: EQUIPMENT.TEK_CHESTPIECE,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Tek Chestpiece",
  },
  {
    name: EQUIPMENT.TEK_GAUNTLETS,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Tek Gauntlets",
  },
  {
    name: EQUIPMENT.TEK_HELMET,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Tek Helmet",
  },
  {
    name: EQUIPMENT.TEK_LEGGINGS,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Tek Leggings",
  },
  {
    name: EQUIPMENT.TEK_SHIELD,
    category: ITEM_CATEGORY.EQUIPMENT,
    english_name: "Tek Shield",
  },
]);
