import { ITEM_CATEGORY } from "./items";

export const RESOURCE = Object.freeze({
  ABSORBENT_SUBSTRATE: "Absorbent Substrate",
  ACHATINA_PASTE: "Achatina Paste",
  ALLOSAURUS_BRAIN: "Allosaurus Brain",
  ALPHA_CARNOTAURUS_ARM: "Alpha Carnotaurus Arm",
  ALPHA_LEEDSICHTHYS_BLUBBER: "Alpha Leedsichthys Blubber",
  ALPHA_MEGALODON_FIN: "Alpha Megalodon Fin",
  ALPHA_MOSASAUR_TOOTH: "Alpha Mosasaur Tooth",
  ALPHA_RAPTOR_CLAW: "Alpha Raptor Claw",
  ALPHA_TUSOTEUTHIS_EYE: "Alpha Tusoteuthis Eye",
  ALPHA_TYRANNOSAUR_TOOTH: "Alpha Tyrannosaur Tooth",
  AMARGASAURUS_SPIKE: "Amargasaurus Spike",
  AMMONITE_BILE: "Ammonite Bile",
  ANGLER_GEL: "Angler Gel",
  ARGENTAVIS_TALON: "Argentavis Talon",
  BASILISK_SCALE: "Basilisk Scale", //
  BASILOSAURUS_BLUBBER: "Basilosaurus Blubber",
  BEER_LIQUID: "Beer Liquid",
  BLACK_PEARL: "Black Pearl",
  BLUE_CRYSTALIZED_SAP: "Blue Crystalized Sap",
  BLUE_GEM: "Blue Gem",
  CAKE_SLICE: "Cake Slice",
  CEMENTING_PASTE: "Cementing Paste",
  CHARGE_BATTERY: "Charge Battery",
  CHITIN_OR_KERATIN: "Chitin Or Keratin",
  CHITIN: "Chitin",
  CLAY: "Clay",
  CONDENSED_GAS: "Condensed Gas",
  CONGEALED_GAS_BALL: "Congealed Gas Ball",
  CORRUPT_HEART: "Corrupt Heart",
  CORRUPTED_NODULE: "Corrupted Nodule",
  CORRUPTED_WOOD: "Corrupted Wood",
  CRAFTED_ELEMENT_DUST: "Crafted Element Dust",
  CRYSTAL_WYVERN_TALON: "Crystal Talon",
  CRYSTAL: "Crystal",
  DEATH_WORM_HORN: "Death Worm Horn",
  DINOSAUR_BONE: "Dinosaur Bone",
  ELECTRONICS: "Electronics",
  ELEMENT_DUST: "Element Dust",
  ELEMENT_ORE: "Element Ore",
  ELEMENT_SHARD: "Element Shard",
  ELEMENT: "Element",
  FIBER: "Fiber",
  FIRE_WYVERN_TALON: "Fire Talon",
  FLINT: "Flint",
  FRAGMENTED_GREEN_GEM: "Fragmented Green Gem",
  FUNGAL_WOOD: "Fungal Wood",
  GASBAGS_BLADDER: "Gasbags bladder",
  GASOLINE_GAS_CRAFTED: "Gasoline Gas Crafted",
  GASOLINE: "Gasoline",
  GIGANOTOSAURUS_HEART: "Giganotosaurus Heart",
  GREEN_GEM: "Green Gem",
  GUNPOWDER: "Gunpowder",
  HIDE: "Hide",
  KERATIN: "Keratin",
  LEECH_BLOOD: "Leech Blood",
  LIGHTNING_WYVERN_TALON: "Lightning Talon",
  MEGALANIA_TOXIN: "Megalania Toxin",
  MEGALODON_TOOTH: "Megalodon Tooth",
  METAL_INGOT: "Metal Ingot",
  METAL_ORE: "Metal Ore",
  OBSIDIAN: "Obsidian",
  OIL: "Oil",
  ORGANIC_POLYMER: "Organic Polymer",
  PELT: "Pelt",
  POISON_WYVERN_TALON: "Poison Talon",
  POLYMER: "Polymer",
  PRESERVING_SALT: "Preserving Salt",
  PRIMAL_CRYSTAL: "Primal Crystal",
  PROPELLANT: "Propellant",
  RAW_SALT: "Raw Salt",
  RED_CRYSTALIZED_SAP: "Red Crystalized Sap",
  RED_GEM: "Red Gem",
  RESIN: "Resin",
  ROCK_DRAKE_FEATHER: "Rock Drake Feather",
  SAND: "Sand",
  SAP: "Sap",
  SAUROPOD_VERTEBRA: "Sauropod Vertebra",
  SCRAP_METAL_INGOT: "Scrap Metal Ingot",
  SCRAP_METAL: "Scrap Metal",
  SHELL_FRAGMENT: "Shell Fragment",
  SILICA_PEARLS: "Silica Pearls",
  SILICATE_CRYSTAL: "Silicate Crystal",
  SILK: "Silk",
  SPARKPOWDER: "Sparkpowder",
  SPINOSAURUS_SAIL: "Spinosaurus Sail",
  STONE: "Stone",
  SULFUR: "Sulfur",
  THATCH: "Thatch",
  THERIZINO_CLAWS: "Therizino Claws",
  THYLACOLEO_CLAW: "Thylacoleo Claw",
  TITANOBOA_VENOM: "Titanoboa Venom",
  TUSOTEUTHIS_OIL: "Tusoteuthis Oil",
  TUSOTEUTHIS_TENTACLE: "Tusoteuthis Tentacle",
  TYRANNOSAURUS_ARM: "Tyrannosaurus Arm",
  UNSTABLE_ELEMENT_SHARD: "Unstable Element Shard",
  UNSTABLE_ELEMENT: "Unstable Element",
  WOOD: "Wood",
  WOOL: "Wool",
  WOOLLY_RHINO_HORN: "Woolly Rhino Horn",
  YUTYRANNUS_LUNGS: "Yutyrannus Lungs",
});

export const CATEGORISED_RESOURCES = Object.freeze([
  {
    name: RESOURCE.OIL,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Oil",
  },
  {
    name: RESOURCE.ABSORBENT_SUBSTRATE,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Absorbent Substrate",
  },
  {
    name: RESOURCE.ACHATINA_PASTE,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Achatina Paste",
  },
  {
    name: RESOURCE.ALLOSAURUS_BRAIN,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Allosaurus Brain",
  },
  {
    name: RESOURCE.ALPHA_CARNOTAURUS_ARM,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Alpha Carnotaurus Arm",
  },
  {
    name: RESOURCE.ALPHA_LEEDSICHTHYS_BLUBBER,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Alpha Leedsichthys Blubber",
  },
  {
    name: RESOURCE.ALPHA_MEGALODON_FIN,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Alpha Megalodon Fin",
  },
  {
    name: RESOURCE.ALPHA_MOSASAUR_TOOTH,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Alpha Mosasaur Tooth",
  },
  {
    name: RESOURCE.ALPHA_RAPTOR_CLAW,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Alpha Raptor Claw",
  },
  {
    name: RESOURCE.ALPHA_TUSOTEUTHIS_EYE,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Alpha Tusoteuthis Eye",
  },
  {
    name: RESOURCE.ALPHA_TYRANNOSAUR_TOOTH,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Alpha Tyrannosaur Tooth",
  },
  {
    name: RESOURCE.AMARGASAURUS_SPIKE,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Amargasaurus Spike",
  },
  {
    name: RESOURCE.AMMONITE_BILE,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Ammonite Bile",
  },
  {
    name: RESOURCE.ANGLER_GEL,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Angler Gel",
  },
  {
    name: RESOURCE.ARGENTAVIS_TALON,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Argentavis Talon",
  },
  {
    name: RESOURCE.BASILISK_SCALE,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Basilisk Scale",
  },
  {
    name: RESOURCE.BASILOSAURUS_BLUBBER,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Basilosaurus Blubber",
  },
  {
    name: RESOURCE.BEER_LIQUID,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Beer Liquid",
  },
  {
    name: RESOURCE.BLACK_PEARL,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Black Pearl",
  },
  {
    name: RESOURCE.BLUE_CRYSTALIZED_SAP,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Blue Crystalized Sap",
  },
  {
    name: RESOURCE.BLUE_GEM,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Blue Gem",
  },
  {
    name: RESOURCE.CAKE_SLICE,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Cake Slice",
  },
  {
    name: RESOURCE.CEMENTING_PASTE,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Cementing Paste",
  },
  {
    name: RESOURCE.CHITIN,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Chitin",
  },
  {
    name: RESOURCE.CHITIN_OR_KERATIN,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Chitin Or Keratin",
  },
  {
    name: RESOURCE.CLAY,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Clay",
  },
  {
    name: RESOURCE.CONDENSED_GAS,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Condensed Gas",
  },
  {
    name: RESOURCE.CONGEALED_GAS_BALL,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Congealed Gas Ball",
  },
  {
    name: RESOURCE.CORRUPT_HEART,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Corrupt Heart",
  },
  {
    name: RESOURCE.CORRUPTED_NODULE,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Corrupted Nodule",
  },
  {
    name: RESOURCE.CORRUPTED_WOOD,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Corrupted Wood",
  },
  {
    name: RESOURCE.CRAFTED_ELEMENT_DUST,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Crafted Element Dust",
  },
  {
    name: RESOURCE.CRYSTAL,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Crystal",
  },
  {
    name: RESOURCE.CRYSTAL_WYVERN_TALON,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Crystal Wyvern Talon",
  },
  {
    name: RESOURCE.DEATH_WORM_HORN,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Death worm Horn",
  },
  {
    name: RESOURCE.DINOSAUR_BONE,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Dinosaur Bone",
  },
  {
    name: RESOURCE.ELECTRONICS,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Electronics",
  },
  {
    name: RESOURCE.ELEMENT,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Element",
  },
  {
    name: RESOURCE.ELEMENT_DUST,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Element Dust",
  },
  {
    name: RESOURCE.ELEMENT_ORE,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Element Ore",
  },
  {
    name: RESOURCE.ELEMENT_SHARD,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Element Shard",
  },
  {
    name: RESOURCE.FIBER,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Fiber",
  },
  {
    name: RESOURCE.FIRE_WYVERN_TALON,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Fire Wyvern Talon",
  },
  {
    name: RESOURCE.FLINT,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Flint",
  },
  {
    name: RESOURCE.FRAGMENTED_GREEN_GEM,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Fragmented Green Gem",
  },
  {
    name: RESOURCE.FUNGAL_WOOD,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Fungal Wood",
  },
  {
    name: RESOURCE.GASBAGS_BLADDER,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Gasbags bladder",
  },
  {
    name: RESOURCE.GASOLINE,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Gasoline",
  },
  {
    name: RESOURCE.GASOLINE_GAS_CRAFTED,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Gasoline Gas Crafted",
  },
  {
    name: RESOURCE.GIGANOTOSAURUS_HEART,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Giganotosaurus Heart",
  },
  {
    name: RESOURCE.GREEN_GEM,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Green Gem",
  },
  {
    name: RESOURCE.GUNPOWDER,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Gunpowder",
  },
  {
    name: RESOURCE.HIDE,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Hide",
  },
  {
    name: RESOURCE.KERATIN,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Keratin",
  },
  {
    name: RESOURCE.LEECH_BLOOD,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Leech Blood",
  },
  {
    name: RESOURCE.LIGHTNING_WYVERN_TALON,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Lightning Wyvern Talon",
  },
  {
    name: RESOURCE.MEGALANIA_TOXIN,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Megalania Toxin",
  },
  {
    name: RESOURCE.MEGALODON_TOOTH,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Megalodon Tooth",
  },
  {
    name: RESOURCE.METAL_ORE,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Metal Ore",
  },
  {
    name: RESOURCE.METAL_INGOT,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Metal Ingot",
  },
  {
    name: RESOURCE.OBSIDIAN,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Obsidian",
  },
  {
    name: RESOURCE.TUSOTEUTHIS_OIL,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Tusoteuthis Oil",
  },
  {
    name: RESOURCE.ORGANIC_POLYMER,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Organic Polymer",
  },
  {
    name: RESOURCE.PELT,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Pelt",
  },
  {
    name: RESOURCE.POISON_WYVERN_TALON,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Poison Wyvern Talon",
  },
  {
    name: RESOURCE.POLYMER,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Polymer",
  },
  {
    name: RESOURCE.PRESERVING_SALT,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Preserving Salt",
  },
  {
    name: RESOURCE.PRIMAL_CRYSTAL,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Primal Crystal",
  },
  {
    name: RESOURCE.CHARGE_BATTERY,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Charge Battery",
  },
  {
    name: RESOURCE.PROPELLANT,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Propellant",
  },
  {
    name: RESOURCE.RAW_SALT,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Raw Salt",
  },
  {
    name: RESOURCE.RED_CRYSTALIZED_SAP,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Red Crystalized Sap",
  },
  {
    name: RESOURCE.RED_GEM,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Red Gem",
  },
  {
    name: RESOURCE.RESIN,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Resin",
  },
  {
    name: RESOURCE.ROCK_DRAKE_FEATHER,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Rock Drake Feather",
  },
  {
    name: RESOURCE.SAND,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Sand",
  },
  {
    name: RESOURCE.SAP,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Sap",
  },
  {
    name: RESOURCE.SAUROPOD_VERTEBRA,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Sauropod Vertebra",
  },
  {
    name: RESOURCE.SCRAP_METAL,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Scrap Metal",
  },
  {
    name: RESOURCE.SCRAP_METAL_INGOT,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Scrap Metal Ingot",
  },
  {
    name: RESOURCE.SHELL_FRAGMENT,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Shell Fragment",
  },
  {
    name: RESOURCE.SILICA_PEARLS,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Silica Pearls",
  },
  {
    name: RESOURCE.SILICATE_CRYSTAL,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Silicate Crystal",
  },
  {
    name: RESOURCE.SILK,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Silk",
  },
  {
    name: RESOURCE.SPARKPOWDER,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Sparkpowder",
  },
  {
    name: RESOURCE.SPINOSAURUS_SAIL,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Spinosaurus Sail",
  },
  {
    name: RESOURCE.STONE,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Stone",
  },
  {
    name: RESOURCE.SULFUR,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Sulfur",
  },
  {
    name: RESOURCE.THATCH,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Thatch",
  },
  {
    name: RESOURCE.THERIZINO_CLAWS,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Therizino Claws",
  },
  {
    name: RESOURCE.THYLACOLEO_CLAW,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Thylacoleo Claw",
  },
  {
    name: RESOURCE.TITANOBOA_VENOM,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Titanoboa Venom",
  },
  {
    name: RESOURCE.TUSOTEUTHIS_TENTACLE,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Tusoteuthis Tentacle",
  },
  {
    name: RESOURCE.TYRANNOSAURUS_ARM,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Tyrannosaurus Arm",
  },
  {
    name: RESOURCE.UNSTABLE_ELEMENT,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Unstable Element",
  },
  {
    name: RESOURCE.UNSTABLE_ELEMENT_SHARD,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Unstable Element Shard",
  },
  {
    name: RESOURCE.WOOD,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Wood",
  },
  {
    name: RESOURCE.WOOL,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Wool",
  },
  {
    name: RESOURCE.WOOLLY_RHINO_HORN,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Woolly Rhino Horn",
  },
  {
    name: RESOURCE.YUTYRANNUS_LUNGS,
    category: ITEM_CATEGORY.RESOURCE,
    english_name: "Yutyrannus Lungs",
  },
]);
