import { ITEM_CATEGORY } from "./items";

export const SADDLE = Object.freeze({
  TAPEJARA_TEK_SADDLE: "Tapejara Tek Saddle",
  ROCK_DRAKE_TEK_SADDLE: "Rock Drake Tek Saddle",
  REX_TEK_SADDLE: "Rex Tek Saddle",
  WOOLLY_RHINO_SADDLE: "Woolly Rhino Saddle",
  YUTYRANNUS_SADDLE: "Yutyrannus Saddle",
  SABERTOOTH_SADDLE: "Sabertooth Saddle",
  SARCO_SADDLE: "Sarco Saddle",
  SNOW_OWL_SADDLE: "Snow Owl Saddle",
  SPINO_SADDLE: "Spino Saddle",
  STEGO_SADDLE: "Stego Saddle",
  TAPEJARA_SADDLE: "Tapejara Saddle",
  TERROR_BIRD_SADDLE: "Terror Bird Saddle",
  THERIZINOSAURUS_SADDLE: "Therizinosaurus Saddle",
  THORNY_DRAGON_SADDLE: "Thorny Dragon Saddle",
  THYLACOLEO_SADDLE: "Thylacoleo Saddle",
  TITANOSAUR_PLATFORM_SADDLE: "Titanosaur Platform Saddle",
  TRIKE_SADDLE: "Trike Saddle",
  TROPEOGNATHUS_SADDLE: "Tropeognathus Saddle",
  TUSOTEUTHIS_SADDLE: "Tusoteuthis Saddle",
  VELONASAUR_SADDLE: "Velonasaur Saddle",
  ROCK_DRAKE_SADDLE: "Rock Drake Saddle",
  ROCK_GOLEM_SADDLE: "Rock Golem Saddle",
  ROLL_RAT_SADDLE: "Roll Rat Saddle",
  PLESIOSAUR_PLATFORM_SADDLE: "Plesiosaur Platform Saddle",
  PLESIOSAUR_SADDLE: "Plesiosaur Saddle",
  PROCOPTODON_SADDLE: "Procoptodon Saddle",
  PTERANODON_SADDLE: "Pteranodon Saddle",
  PULMONOSCORPIUS_SADDLE: "Pulmonoscorpius Saddle",
  QUETZ_PLATFORM_SADDLE: "Quetz Platform Saddle",
  QUETZ_SADDLE: "Quetz Saddle",
  RAPTOR_SADDLE: "Raptor Saddle",
  RAVAGER_SADDLE: "Ravager Saddle",
  REX_SADDLE: "Rex Saddle",
  RHYNIOGNATHA_SADDLE: "Rhyniognatha Saddle",
  PACHY_SADDLE: "Pachy Saddle",
  PACHYRHINOSAURUS_SADDLE: "Pachyrhinosaurus Saddle",
  PARACER_PLATFORM_SADDLE: "Paracer Platform Saddle",
  PARACER_SADDLE: "Paracer Saddle",
  PARASAUR_SADDLE: "Parasaur Saddle",
  PELAGORNIS_SADDLE: "Pelagornis Saddle",
  PHIOMIA_SADDLE: "Phiomia Saddle",
  MORELLATOPS_SADDLE: "Morellatops Saddle",
  MOSASAUR_PLATFORM_SADDLE: "Mosasaur Platform Saddle",
  MOSASAUR_SADDLE: "Mosasaur Saddle",
  MAEWING_SADDLE: "Maewing Saddle",
  MAGMASAUR_SADDLE: "Magmasaur Saddle",
  MAMMOTH_SADDLE: "Mammoth Saddle",
  MANAGARMR_SADDLE: "Managarmr Saddle",
  MANTA_SADDLE: "Manta Saddle",
  MANTIS_SADDLE: "Mantis Saddle",
  MEGACHELON_PLATFORM_SADDLE: "Megachelon Platform Saddle",
  MEGALANIA_SADDLE: "Megalania Saddle",
  MEGALOCEROS_SADDLE: "Megaloceros Saddle",
  MEGALODON_SADDLE: "Megalodon Saddle",
  MEGALOSAURUS_SADDLE: "Megalosaurus Saddle",
  MEGATHERIUM_SADDLE: "Megatherium Saddle",
  ICE_TITAN_SADDLE: "Ice Titan Saddle",
  ICHTHYOSAURUS_SADDLE: "Ichthyosaurus Saddle",
  IGUANODON_SADDLE: "Iguanodon Saddle",
  KAPROSUCHUS_SADDLE: "Kaprosuchus Saddle",
  KARKINOS_SADDLE: "Karkinos Saddle",
  LYMANTRIA_SADDLE: "Lymantria Saddle",
  GIGANOTOSAURUS_SADDLE: "Giganotosaurus Saddle",
  GIGANTORAPTOR_SADDLE: "Gigantoraptor Saddle",
  GASBAGS_SADDLE: "Gasbags Saddle",
  GACHA_SADDLE: "Gacha Saddle",
  GALLIMIMUS_SADDLE: "Gallimimus Saddle",
  FOREST_TITAN_SADDLE: "Forest Titan Saddle",
  DOEDICURUS_SADDLE: "Doedicurus Saddle",
  DUNKLEOSTEUS_SADDLE: "Dunkleosteus Saddle",
  EQUUS_SADDLE: "Equus Saddle",
  FASOLASUCHUS_SADDLE: "Fasolasuchus Saddle",
  DIRE_BEAR_SADDLE: "Dire Bear Saddle",
  DESERT_TITAN_SADDLE: "Desert Titan Saddle",
  DESMODUS_SADDLE: "Desmodus Saddle",
  DIPLODOCUS_SADDLE: "Diplodocus Saddle",
  DAEODON_SADDLE: "Daeodon Saddle",
  DEINONYCHUS_SADDLE: "Deinonychus Saddle",
  ALLOSAURUS_SADDLE: "Allosaurus Saddle",
  AMARGASAURUS_SADDLE: "Amargasaurus Saddle",
  ANDREWSARCHUS_SADDLE: "Andrewsarchus Saddle",
  ANKYLO_SADDLE: "Ankylo Saddle",
  ARANEO_SADDLE: "Araneo Saddle",
  ARGENTAVIS_SADDLE: "Argentavis Saddle",
  ARTHROPLUERA_SADDLE: "Arthropluera Saddle",
  BARYONYX_SADDLE: "Baryonyx Saddle",
  BASILISK_SADDLE: "Basilisk Saddle",
  BASILOSAURUS_SADDLE: "Basilosaurus Saddle",
  BEELZEBUFO_SADDLE: "Beelzebufo Saddle",
  BRONTO_PLATFORM_SADDLE: "Bronto Platform Saddle",
  BRONTO_SADDLE: "Bronto Saddle",
  ASTROCETUS_TEK_SADDLE: "Astrocetus Tek Saddle",
  ASTRODELPHIS_STARWING_SADDLE: "Astrodelphis Starwing Saddle",
});

export const CATEGORISED_SADDLES = Object.freeze([
  {
    name: SADDLE.TAPEJARA_TEK_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Tapejara Tek Saddle",
  },
  {
    name: SADDLE.ROCK_DRAKE_TEK_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Rock Drake Tek Saddle",
  },
  {
    name: SADDLE.REX_TEK_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Rex Tek Saddle",
  },
  {
    name: SADDLE.WOOLLY_RHINO_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Woolly Rhino Saddle",
  },
  {
    name: SADDLE.YUTYRANNUS_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Yutyrannus Saddle",
  },
  {
    name: SADDLE.SABERTOOTH_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Sabertooth Saddle",
  },
  {
    name: SADDLE.SARCO_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Sarco Saddle",
  },
  {
    name: SADDLE.SNOW_OWL_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Snow Owl Saddle",
  },
  {
    name: SADDLE.SPINO_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Spino Saddle",
  },
  {
    name: SADDLE.STEGO_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Stego Saddle",
  },
  {
    name: SADDLE.TAPEJARA_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Tapejara Saddle",
  },
  {
    name: SADDLE.TERROR_BIRD_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Terror Bird Saddle",
  },
  {
    name: SADDLE.THERIZINOSAURUS_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Therizinosaurus Saddle",
  },
  {
    name: SADDLE.THORNY_DRAGON_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Thorny Dragon Saddle",
  },
  {
    name: SADDLE.THYLACOLEO_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Thylacoleo Saddle",
  },
  {
    name: SADDLE.TITANOSAUR_PLATFORM_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Titanosaur Platform Saddle",
  },
  {
    name: SADDLE.TRIKE_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Trike Saddle",
  },
  {
    name: SADDLE.TROPEOGNATHUS_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Tropeognathus Saddle",
  },
  {
    name: SADDLE.TUSOTEUTHIS_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Tusoteuthis Saddle",
  },
  {
    name: SADDLE.VELONASAUR_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Velonasaur Saddle",
  },
  {
    name: SADDLE.ROCK_DRAKE_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Rock Drake Saddle",
  },
  {
    name: SADDLE.ROCK_GOLEM_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Rock Golem Saddle",
  },
  {
    name: SADDLE.ROLL_RAT_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Roll Rat Saddle",
  },
  {
    name: SADDLE.PLESIOSAUR_PLATFORM_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Plesiosaur Platform Saddle",
  },
  {
    name: SADDLE.PLESIOSAUR_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Plesiosaur Saddle",
  },
  {
    name: SADDLE.PROCOPTODON_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Procoptodon Saddle",
  },
  {
    name: SADDLE.PTERANODON_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Pteranodon Saddle",
  },
  {
    name: SADDLE.PULMONOSCORPIUS_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Pulmonoscorpius Saddle",
  },
  {
    name: SADDLE.QUETZ_PLATFORM_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Quetz Platform Saddle",
  },
  {
    name: SADDLE.QUETZ_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Quetz Saddle",
  },
  {
    name: SADDLE.RAPTOR_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Raptor Saddle",
  },
  {
    name: SADDLE.RAVAGER_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Ravager Saddle",
  },
  {
    name: SADDLE.REX_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Rex Saddle",
  },
  {
    name: SADDLE.RHYNIOGNATHA_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Rhyniognatha Saddle",
  },
  {
    name: SADDLE.PACHY_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Pachy Saddle",
  },
  {
    name: SADDLE.PACHYRHINOSAURUS_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Pachyrhinosaurus Saddle",
  },
  {
    name: SADDLE.PARACER_PLATFORM_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Paracer Platform Saddle",
  },
  {
    name: SADDLE.PARACER_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Paracer Saddle",
  },
  {
    name: SADDLE.PARASAUR_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Parasaur Saddle",
  },
  {
    name: SADDLE.PELAGORNIS_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Pelagornis Saddle",
  },
  {
    name: SADDLE.PHIOMIA_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Phiomia Saddle",
  },
  {
    name: SADDLE.MORELLATOPS_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Morellatops Saddle",
  },
  {
    name: SADDLE.MOSASAUR_PLATFORM_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Mosasaur Platform Saddle",
  },
  {
    name: SADDLE.MOSASAUR_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Mosasaur Saddle",
  },
  {
    name: SADDLE.MAEWING_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Maewing Saddle",
  },
  {
    name: SADDLE.MAGMASAUR_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Magmasaur Saddle",
  },
  {
    name: SADDLE.MAMMOTH_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Mammoth Saddle",
  },
  {
    name: SADDLE.MANAGARMR_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Managarmr Saddle",
  },
  {
    name: SADDLE.MANTA_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Manta Saddle",
  },
  {
    name: SADDLE.MANTIS_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Mantis Saddle",
  },
  {
    name: SADDLE.MEGACHELON_PLATFORM_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Megachelon Platform Saddle",
  },
  {
    name: SADDLE.MEGALANIA_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Megalania Saddle",
  },
  {
    name: SADDLE.MEGALOCEROS_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Megaloceros Saddle",
  },
  {
    name: SADDLE.MEGALODON_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Megalodon Saddle",
  },
  {
    name: SADDLE.MEGALOSAURUS_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Megalosaurus Saddle",
  },
  {
    name: SADDLE.MEGATHERIUM_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Megatherium Saddle",
  },
  {
    name: SADDLE.ICE_TITAN_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Ice Titan Saddle",
  },
  {
    name: SADDLE.ICHTHYOSAURUS_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Ichthyosaurus Saddle",
  },
  {
    name: SADDLE.IGUANODON_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Iguanodon Saddle",
  },
  {
    name: SADDLE.KAPROSUCHUS_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Kaprosuchus Saddle",
  },
  {
    name: SADDLE.KARKINOS_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Karkinos Saddle",
  },
  {
    name: SADDLE.LYMANTRIA_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Lymantria Saddle",
  },
  {
    name: SADDLE.GIGANOTOSAURUS_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Giganotosaurus Saddle",
  },
  {
    name: SADDLE.GIGANTORAPTOR_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Gigantoraptor Saddle",
  },
  {
    name: SADDLE.GASBAGS_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Gasbags Saddle",
  },
  {
    name: SADDLE.GACHA_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Gacha Saddle",
  },
  {
    name: SADDLE.GALLIMIMUS_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Gallimimus Saddle",
  },
  {
    name: SADDLE.FOREST_TITAN_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Forest Titan Saddle",
  },
  {
    name: SADDLE.DOEDICURUS_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Doedicurus Saddle",
  },
  {
    name: SADDLE.DUNKLEOSTEUS_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Dunkleosteus Saddle",
  },
  {
    name: SADDLE.EQUUS_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Equus Saddle",
  },
  {
    name: SADDLE.FASOLASUCHUS_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Fasolasuchus Saddle",
  },
  {
    name: SADDLE.DIRE_BEAR_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Dire Bear Saddle",
  },
  {
    name: SADDLE.DESERT_TITAN_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Desert Titan Saddle",
  },
  {
    name: SADDLE.DESMODUS_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Desmodus Saddle",
  },
  {
    name: SADDLE.DIPLODOCUS_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Diplodocus Saddle",
  },
  {
    name: SADDLE.DAEODON_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Daeodon Saddle",
  },
  {
    name: SADDLE.DEINONYCHUS_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Deinonychus Saddle",
  },
  {
    name: SADDLE.ALLOSAURUS_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Allosaurus Saddle",
  },
  {
    name: SADDLE.AMARGASAURUS_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Amargasaurus Saddle",
  },
  {
    name: SADDLE.ANDREWSARCHUS_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Andrewsarchus Saddle",
  },
  {
    name: SADDLE.ANKYLO_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Ankylo Saddle",
  },
  {
    name: SADDLE.ARANEO_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Araneo Saddle",
  },
  {
    name: SADDLE.ARGENTAVIS_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Argentavis Saddle",
  },
  {
    name: SADDLE.ARTHROPLUERA_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Arthropluera Saddle",
  },
  {
    name: SADDLE.BARYONYX_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Baryonyx Saddle",
  },
  {
    name: SADDLE.BASILISK_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Basilisk Saddle",
  },
  {
    name: SADDLE.BASILOSAURUS_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Basilosaurus Saddle",
  },
  {
    name: SADDLE.BEELZEBUFO_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Beelzebufo Saddle",
  },
  {
    name: SADDLE.BRONTO_PLATFORM_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Bronto Platform Saddle",
  },
  {
    name: SADDLE.BRONTO_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Bronto Saddle",
  },
  {
    name: SADDLE.ASTROCETUS_TEK_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Astrocetus Tek Saddle",
  },
  {
    name: SADDLE.ASTRODELPHIS_STARWING_SADDLE,
    category: ITEM_CATEGORY.SADDLE,
    english_name: "Astrodelphis Starwing Saddle",
  },
]);
