import { ITEM_CATEGORY } from "./items";

export const WEAPON = Object.freeze({
  BOLA: "Bola",
  BOOMERANG: "Boomerang",
  C4_REMOTE_DETONATOR: "C4 Remote Detonator",
  CLUSTER_GRENADE: "Cluster Grenade",
  CRUISE_MISSILE: "Cruise Missile",
  EMPTY_CRYOPOD: "Empty Cryopod",
  FISH_NET: "Fish Net",
  FLARE_GUN: "Flare Gun",
  GLOW_STICK: "Glow Stick",
  GRENADE: "Grenade",
  IMPROVISED_EXPLOSIVE_DEVICE: "Improvised Explosive Device",
  LASSO: "Lasso",
  MAGNIFYING_GLASS: "Magnifying Glass",
  OIL_JAR: "Oil Jar",
  PAINTBRUSH: "Paintbrush",
  PLANT_SPECIES_Z_FRUIT: "Plant Species Z Fruit",
  POISON_GRENADE: "Poison Grenade",
  ASSAULT_RIFLE: "Assault Rifle",
  BOW: "Bow",
  CAMERA: "Camera",
  CHAINSAW: "Chainsaw",
  CHARGE_LANTERN: "Charge Lantern",
  CLIMBING_PICK: "Climbing Pick",
  COMPOUND_BOW: "Compound Bow",
  CROSSBOW: "Crossbow",
  ELECTRIC_PROD: "Electric Prod",
  FABRICATED_PISTOL: "Fabricated Pistol",
  FABRICATED_SNIPER_RIFLE: "Fabricated Sniper Rifle",
  FISHING_ROD: "Fishing Rod",
  FLAMETHROWER: "Flamethrower",
  HARPOON_LAUNCHER: "Harpoon Launcher",
  LANCE: "Lance",
  LONGNECK_RIFLE: "Longneck Rifle",
  METAL_HATCHET: "Metal Hatchet",
  METAL_PICK: "Metal Pick",
  METAL_SICKLE: "Metal Sickle",
  MINIGUN: "Minigun",
  MINING_DRILL: "Mining Drill",
  PIKE: "Pike",
  PUMP_ACTION_SHOTGUN: "Pump-Action Shotgun",
  SCOUT_REMOTE: "Scout Remote",
  SHOTGUN: "Shotgun",
  SHOVEL: "Shovel",
  SIMPLE_PISTOL: "Simple Pistol",
  SLINGSHOT: "Slingshot",
  STONE_HATCHET: "Stone Hatchet",
  STONE_PICK: "Stone Pick",
  SWORD: "Sword",
  TEK_BOW: "Tek Bow",
  TEK_CLAWS: "Tek Claws",
  TEK_GRENADE_LAUNCHER: "Tek Grenade Launcher",
  TEK_PHASE_PISTOL: "Tek Phase Pistol",
  TEK_RAILGUN: "Tek Railgun",
  TEK_RIFLE: "Tek Rifle",
  TEK_SWORD: "Tek Sword",
  TORCH: "Torch",
  WHIP: "Whip",
  WOODEN_CLUB: "Wooden Club",
  ROCKET_LAUNCHER: "Rocket Launcher",
  SCISSORS: "Scissors",
  SMOKE_GRENADE: "Smoke Grenade",
  SPEAR: "Spear",
  SPRAY_PAINTER: "Spray Painter",
  SPYGLASS: "Spyglass",
  TAXIDERMY_TOOL: "Taxidermy Tool",
  TEK_BINOCULARS: "Tek Binoculars",
  TEK_GRAVITY_GRENADE: "Tek Gravity Grenade",
  TEK_GRENADE: "Tek Grenade",
  TRIPWIRE_ALARM_TRAP: "Tripwire Alarm Trap",
  TRIPWIRE_CHARGE_FLARE_TRAP: "Tripwire Charge Flare Trap",
  TRIPWIRE_NARCOTIC_TRAP: "Tripwire Narcotic Trap",
});

export const CATEGORISED_WEAPONS = Object.freeze([
  {
    name: WEAPON.BOLA,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Bola",
  },
  {
    name: WEAPON.BOOMERANG,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Boomerang",
  },
  {
    name: WEAPON.C4_REMOTE_DETONATOR,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "C4 Remote Detonator",
  },
  {
    name: WEAPON.CLUSTER_GRENADE,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Cluster Grenade",
  },
  {
    name: WEAPON.CRUISE_MISSILE,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Cruise Missile",
  },
  {
    name: WEAPON.EMPTY_CRYOPOD,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Empty Cryopod",
  },
  {
    name: WEAPON.FISH_NET,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Fish Net",
  },
  {
    name: WEAPON.FLARE_GUN,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Flare Gun",
  },
  {
    name: WEAPON.GLOW_STICK,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Glow Stick",
  },
  {
    name: WEAPON.GRENADE,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Grenade",
  },
  {
    name: WEAPON.IMPROVISED_EXPLOSIVE_DEVICE,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Improvised Explosive Device",
  },
  {
    name: WEAPON.LASSO,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Lasso",
  },
  {
    name: WEAPON.MAGNIFYING_GLASS,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Magnifying Glass",
  },
  {
    name: WEAPON.OIL_JAR,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Oil Jar",
  },
  {
    name: WEAPON.PAINTBRUSH,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Paintbrush",
  },
  {
    name: WEAPON.PLANT_SPECIES_Z_FRUIT,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Plant Species Z Fruit",
  },
  {
    name: WEAPON.POISON_GRENADE,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Poison Grenade",
  },
  {
    name: WEAPON.ASSAULT_RIFLE,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Assault Rifle",
  },
  {
    name: WEAPON.BOW,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Bow",
  },
  {
    name: WEAPON.CAMERA,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Camera",
  },
  {
    name: WEAPON.CHAINSAW,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Chainsaw",
  },
  {
    name: WEAPON.CHARGE_LANTERN,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Charge Lantern",
  },
  {
    name: WEAPON.CLIMBING_PICK,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Climbing Pick",
  },
  {
    name: WEAPON.COMPOUND_BOW,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Compound Bow",
  },
  {
    name: WEAPON.CROSSBOW,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Crossbow",
  },
  {
    name: WEAPON.ELECTRIC_PROD,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Electric Prod",
  },
  {
    name: WEAPON.FABRICATED_PISTOL,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Fabricated Pistol",
  },
  {
    name: WEAPON.FABRICATED_SNIPER_RIFLE,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Fabricated Sniper Rifle",
  },
  {
    name: WEAPON.FISHING_ROD,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Fishing Rod",
  },
  {
    name: WEAPON.FLAMETHROWER,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Flamethrower",
  },
  {
    name: WEAPON.HARPOON_LAUNCHER,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Harpoon Launcher",
  },
  {
    name: WEAPON.LANCE,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Lance",
  },
  {
    name: WEAPON.LONGNECK_RIFLE,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Longneck Rifle",
  },
  {
    name: WEAPON.METAL_HATCHET,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Metal Hatchet",
  },
  {
    name: WEAPON.METAL_PICK,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Metal Pick",
  },
  {
    name: WEAPON.METAL_SICKLE,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Metal Sickle",
  },
  {
    name: WEAPON.MINIGUN,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Minigun",
  },
  {
    name: WEAPON.MINING_DRILL,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Mining Drill",
  },
  {
    name: WEAPON.PIKE,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Pike",
  },
  {
    name: WEAPON.PUMP_ACTION_SHOTGUN,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Pump-Action Shotgun",
  },
  {
    name: WEAPON.SCOUT_REMOTE,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Scout Remote",
  },
  {
    name: WEAPON.SHOTGUN,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Shotgun",
  },
  {
    name: WEAPON.SHOVEL,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Shovel",
  },
  {
    name: WEAPON.SIMPLE_PISTOL,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Simple Pistol",
  },
  {
    name: WEAPON.SLINGSHOT,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Slingshot",
  },
  {
    name: WEAPON.STONE_HATCHET,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Stone Hatchet",
  },
  {
    name: WEAPON.STONE_PICK,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Stone Pick",
  },
  {
    name: WEAPON.SWORD,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Sword",
  },
  {
    name: WEAPON.TEK_BOW,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Tek Bow",
  },
  {
    name: WEAPON.TEK_CLAWS,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Tek Claws",
  },
  {
    name: WEAPON.TEK_GRENADE_LAUNCHER,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Tek Grenade Launcher",
  },
  {
    name: WEAPON.TEK_PHASE_PISTOL,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Tek Phase Pistol",
  },
  {
    name: WEAPON.TEK_RAILGUN,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Tek Railgun",
  },
  {
    name: WEAPON.TEK_RIFLE,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Tek Rifle",
  },
  {
    name: WEAPON.TEK_SWORD,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Tek Sword",
  },
  {
    name: WEAPON.TORCH,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Torch",
  },
  {
    name: WEAPON.WHIP,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Whip",
  },
  {
    name: WEAPON.WOODEN_CLUB,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Wooden Club",
  },
  {
    name: WEAPON.ROCKET_LAUNCHER,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Rocket Launcher",
  },
  {
    name: WEAPON.SCISSORS,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Scissors",
  },
  {
    name: WEAPON.SMOKE_GRENADE,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Smoke Grenade",
  },
  {
    name: WEAPON.SPEAR,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Spear",
  },
  {
    name: WEAPON.SPRAY_PAINTER,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Spray Painter",
  },
  {
    name: WEAPON.SPYGLASS,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Spyglass",
  },
  {
    name: WEAPON.TAXIDERMY_TOOL,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Taxidermy Tool",
  },
  {
    name: WEAPON.TEK_BINOCULARS,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Tek Binoculars",
  },
  {
    name: WEAPON.TEK_GRAVITY_GRENADE,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Tek Gravity Grenade",
  },
  {
    name: WEAPON.TEK_GRENADE,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Tek Grenade",
  },
  {
    name: WEAPON.TRIPWIRE_ALARM_TRAP,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Tripwire Alarm Trap",
  },
  {
    name: WEAPON.TRIPWIRE_CHARGE_FLARE_TRAP,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Tripwire Charge Flare Trap",
  },
  {
    name: WEAPON.TRIPWIRE_NARCOTIC_TRAP,
    category: ITEM_CATEGORY.WEAPON,
    english_name: "Tripwire Narcotic Trap",
  },
]);
