export const CREATURE_CATEGORY = Object.freeze({
  CLIMBER: "Climber",
  DAMAGE_DEALER: "Damage Dealer",
  FARMER: "Farmer",
  FLYER: "Flyer",
  HEALER: "Healer",
  MISC: "Misc",
  SHOULDER_PETS: "Shoulder Pets",
  SOAKER: "Soaker",
  SUPPORTER: "Supporter",
  TAMING_BREEDING: "Taming & Breeding",
  WATER: "Water",
});

export const dinosaurCategories = Object.values(CREATURE_CATEGORY);

export const CREATURE = Object.freeze({
  ACHATINA: "Achatina",
  ALLOSAURUS: "Allosaurus",
  AMARGASAURUS: "Amargasaurus",
  ANDREWSARCHUS: "Andrewsarchus",
  ANGLERFISH: "Anglerfish",
  ANKYLOSAURUS: "Ankylosaurus",
  ARANEO: "Araneo",
  ARCHAEOPTERYX: "Archaeopteryx",
  ARGENTAVIS: "Argentavis",
  ARTHROPLUERA: "Arthropluera",
  ASTROCETUS: "Astrocetus",
  ASTRODELPHIS: "Astrodelphis",
  BARYONYX: "Baryonyx",
  BASILOSAURUS: "Basilosaurus",
  BEELZEBUFO: "Beelzebufo",
  BLOODSTALKER: "Bloodstalker",
  BRONTOSAURUS: "Brontosaurus",
  CARBONEMYS: "Carbonemys",
  CARCHARODONTOSAURUS: "Carcharodontosaurus",
  CARNOTAURUS: "Carnotaurus",
  CASTOROIDES: "Castoroides",
  CERATOSAURUS: "Ceratosaurus",
  CHALICOTHERIUM: "Chalicotherium",
  CNIDARIA: "Cnidaria",
  COELACANTH: "Coelacanth",
  COMPY: "Compy",
  COSMO: "Cosmo",
  DAEODON: "Daeodon",
  DEINONYCHUS: "Deinonychus",
  DEINOSUCHUS: "Deinosuchus",
  DESMODUS: "Desmodus",
  DILOPHOSAUR: "Dilophosaur",
  DIMETRODON: "Dimetrodon",
  DIMORPHODON: "Dimorphodon",
  DINOPITHECUS: "Dinopithecus",
  DIPLOCAULUS: "Diplocaulus",
  DIPLODOCUS: "Diplodocus",
  DIRE_BEAR: "Dire Bear",
  DIREWOLF: "Direwolf",
  DODO: "Dodo",
  DOEDICURUS: "Doedicurus",
  DUNG_BEETLE: "Dung Beetle",
  DUNKLEOSTEUS: "Dunkleosteus",
  ELECTROPHORUS: "Electrophorus",
  ENFORCER: "Enforcer",
  EQUUS: "Equus",
  FASOLASUCHUS: "Fasolasuchus",
  FEATHERLIGHT: "Featherlight",
  FENRIR: "Fenrir",
  FEROX: "Ferox",
  FJORDHAWK: "Fjordhawk",
  GACHA: "Gacha",
  GASBAGS: "Gasbags",
  GIANT_QUEEN_BEE: "Giant Queen Bee",
  GIGANOTOSAURUS: "Giganotosaurus",
  GIGANTOPITHECUS: "Gigantopithecus",
  GIGANTORAPTOR: "Gigantoraptor",
  GLOWTAIL: "Glowtail",
  GRIFFIN: "Griffin",
  HESPERORNIS: "Hesperornis",
  ICHTHYORNIS: "Ichthyornis",
  ICHTHYOSAURUS: "Ichthyosaurus",
  IGUANODON: "Iguanodon",
  KAIRUKU: "Kairuku",
  KAPROSUCHUS: "Kaprosuchus",
  KARKINOS: "Karkinos",
  KENTROSAURUS: "Kentrosaurus",
  LEEDSICHTHYS: "Leedsichthys",
  LIOPLEURODON: "Liopleurodon",
  LYMANTRIA: "Lymantria",
  LYSTROSAURUS: "Lystrosaurus",
  MAEWING: "Maewing",
  MAGMASAUR: "Magmasaur",
  MAMMOTH: "Mammoth",
  MANAGARMR: "Managarmr",
  MANTIS: "Mantis",
  MEGACHELON: "Megachelon",
  MEGALANIA: "Megalania",
  MEGALOCEROS: "Megaloceros",
  MEGALODON: "Megalodon",
  MEGALOSAURUS: "Megalosaurus",
  MEGANEURA: "Meganeura",
  MEGATHERIUM: "Megatherium",
  MEK: "Mek",
  MESOPITHECUS: "Mesopithecus",
  MICRORAPTOR: "Microraptor",
  MORELLATOPS: "Morellatops",
  MOSASAURUS: "Mosasaurus",
  MOSCHOPS: "Moschops",
  OASISAUR: "Oasisaur",
  ONYC: "Onyc",
  OTTER: "Otter",
  OVIRAPTOR: "Oviraptor",
  OVIS: "Ovis",
  PACHY: "Pachy",
  PACHYRHINOSAURUS: "Pachyrhinosaurus",
  PARACERATHERIUM: "Paraceratherium",
  PARASAUR: "Parasaur",
  PEGOMASTAX: "Pegomastax",
  PELAGORNIS: "Pelagornis",
  PHIOMIA: "Phiomia",
  PHOENIX: "Phoenix",
  PIRANHA: "Piranha",
  PLESIOSAUR: "Plesiosaur",
  PROCOPTODON: "Procoptodon",
  PTERANODON: "Pteranodon",
  PULMONOSCORPIUS: "Pulmonoscorpius",
  PURLOVIA: "Purlovia",
  PYROMANE: "Pyromane",
  QUETZAL: "Quetzal",
  RAPTOR: "Raptor",
  RAVAGER: "Ravager",
  REAPER_QUEEN: "Reaper Queen",
  REX: "Rex",
  RHYNIOGNATHA: "Rhyniognatha",
  ROCK_DRAKE: "Rock Drake",
  ROLL_RAT: "Roll Rat",
  SABERTOOTH: "Sabertooth",
  SABERTOOTH_SALMON: "Sabertooth Salmon",
  SARCO: "Sarco",
  SHADOWMANE: "Shadowmane",
  SHASTASAURUS: "Shastasaurus",
  SHINEHORN: "Shinehorn",
  SINOMACROPS: "Sinomacrops",
  SNOW_OWL: "Snow Owl",
  SPINO: "Spino",
  STEGOSAURUS: "Stegosaurus",
  TAPEJARA: "Tapejara",
  TEK_STRYDER: "Tek Stryder",
  TERROR_BIRD: "Terror Bird",
  THERIZINOSAUR: "Therizinosaur",
  THORNY_DRAGON: "Thorny Dragon",
  THYLACOLEO: "Thylacoleo",
  TITANOBOA: "Titanoboa",
  TITANOSAUR: "Titanosaur",
  TRICERATOPS: "Triceratops",
  TROODON: "Troodon",
  TROPEOGNATHUS: "Tropeognathus",
  TUSOTEUTHIS: "Tusoteuthis",
  VELONASAUR: "Velonasaur",
  VOIDWYRM: "Voidwyrm",
  WOOLLY_RHINO: "Woolly Rhino",
  WYVERN: "Wyvern",
  XIPHACTINUS: "Xiphactinus",
  YETI: "Yeti",
  YI_LING: "Yi Ling",
  YUTYRANNUS: "Yutyrannus",
});

export const creatures = Object.values(CREATURE);

export const CATEGORISED_CREATURES = Object.freeze([
  {
    name: CREATURE.COSMO,
    category: CREATURE_CATEGORY.SHOULDER_PETS,
    english_name: "Cosmo",
  },
  {
    name: CREATURE.YI_LING,
    category: CREATURE_CATEGORY.DAMAGE_DEALER,
    english_name: "Yi Ling",
  },
  {
    name: CREATURE.MOSASAURUS,
    category: CREATURE_CATEGORY.WATER,
    english_name: "Mosasaurus",
  },
  {
    name: CREATURE.LIOPLEURODON,
    category: CREATURE_CATEGORY.WATER,
    english_name: "Liopleurodon",
  },
  {
    name: CREATURE.PIRANHA,
    category: CREATURE_CATEGORY.WATER,
    english_name: "Piranha",
  },
  {
    name: CREATURE.XIPHACTINUS,
    category: CREATURE_CATEGORY.DAMAGE_DEALER,
    english_name: "Xiphactinus",
  },
  {
    name: CREATURE.DESMODUS,
    category: CREATURE_CATEGORY.FLYER,
    english_name: "Desmodus",
  },
  {
    name: CREATURE.HESPERORNIS,
    category: CREATURE_CATEGORY.MISC,
    english_name: "Hesperornis",
  },
  {
    name: CREATURE.ICHTHYOSAURUS,
    category: CREATURE_CATEGORY.WATER,
    english_name: "Ichthyosaurus",
  },
  {
    name: CREATURE.PTERANODON,
    category: CREATURE_CATEGORY.FLYER,
    english_name: "Pteranodon",
  },
  {
    name: CREATURE.SHASTASAURUS,
    category: CREATURE_CATEGORY.WATER,
    english_name: "Shastasaurus",
  },
  {
    name: CREATURE.DEINOSUCHUS,
    category: CREATURE_CATEGORY.WATER,
    english_name: "Deinosuchus",
  },
  {
    name: CREATURE.DIMORPHODON,
    category: CREATURE_CATEGORY.SHOULDER_PETS,
    english_name: "Dimorphodon",
  },
  {
    name: CREATURE.DUNKLEOSTEUS,
    category: CREATURE_CATEGORY.FARMER,
    english_name: "Dunkleosteus",
  },
  {
    name: CREATURE.PARACERATHERIUM,
    category: CREATURE_CATEGORY.SOAKER,
    english_name: "Paraceratherium",
  },
  {
    name: CREATURE.TEK_STRYDER,
    category: CREATURE_CATEGORY.FARMER,
    english_name: "Tek Stryder",
  },
  {
    name: CREATURE.BLOODSTALKER,
    category: CREATURE_CATEGORY.CLIMBER,
    english_name: "Bloodstalker",
  },
  {
    name: CREATURE.KARKINOS,
    category: CREATURE_CATEGORY.FARMER,
    english_name: "Karkinos",
  },
  {
    name: CREATURE.FASOLASUCHUS,
    category: CREATURE_CATEGORY.DAMAGE_DEALER,
    english_name: "Fasolasuchus",
  },
  {
    name: CREATURE.GIGANTOPITHECUS,
    category: CREATURE_CATEGORY.MISC,
    english_name: "Gigantopithecus",
  },
  {
    name: CREATURE.MEK,
    category: CREATURE_CATEGORY.DAMAGE_DEALER,
    english_name: "Mek",
  },
  {
    name: CREATURE.CASTOROIDES,
    category: CREATURE_CATEGORY.FARMER,
    english_name: "Castoroides",
  },
  {
    name: CREATURE.BRONTOSAURUS,
    category: CREATURE_CATEGORY.FARMER,
    english_name: "Brontosaurus",
  },
  {
    name: CREATURE.SABERTOOTH,
    category: CREATURE_CATEGORY.MISC,
    english_name: "Sabertooth",
  },
  {
    name: CREATURE.ROCK_DRAKE,
    category: CREATURE_CATEGORY.CLIMBER,
    english_name: "Rock Drake",
  },
  {
    name: CREATURE.TRICERATOPS,
    category: CREATURE_CATEGORY.SOAKER,
    english_name: "Triceratops",
  },
  {
    name: CREATURE.WOOLLY_RHINO,
    category: CREATURE_CATEGORY.DAMAGE_DEALER,
    english_name: "Woolly Rhino",
  },
  {
    name: CREATURE.REX,
    category: CREATURE_CATEGORY.DAMAGE_DEALER,
    english_name: "Rex",
  },
  {
    name: CREATURE.STEGOSAURUS,
    category: CREATURE_CATEGORY.SOAKER,
    english_name: "Stegosaurus",
  },
  {
    name: CREATURE.MANTIS,
    category: CREATURE_CATEGORY.FARMER,
    english_name: "Mantis",
  },
  {
    name: CREATURE.MEGALANIA,
    category: CREATURE_CATEGORY.DAMAGE_DEALER,
    english_name: "Megalania",
  },
  {
    name: CREATURE.CHALICOTHERIUM,
    category: CREATURE_CATEGORY.MISC,
    english_name: "Chalicotherium",
  },
  {
    name: CREATURE.ARTHROPLUERA,
    category: CREATURE_CATEGORY.DAMAGE_DEALER,
    english_name: "Arthropluera",
  },
  {
    name: CREATURE.KAIRUKU,
    category: CREATURE_CATEGORY.MISC,
    english_name: "Kairuku",
  },
  {
    name: CREATURE.DUNG_BEETLE,
    category: CREATURE_CATEGORY.FARMER,
    english_name: "Dung Beetle",
  },
  {
    name: CREATURE.FEROX,
    category: CREATURE_CATEGORY.DAMAGE_DEALER,
    english_name: "Ferox",
  },
  {
    name: CREATURE.GLOWTAIL,
    category: CREATURE_CATEGORY.SHOULDER_PETS,
    english_name: "Glowtail",
  },
  {
    name: CREATURE.DODO,
    category: CREATURE_CATEGORY.MISC,
    english_name: "Dodo",
  },
  {
    name: CREATURE.DIPLOCAULUS,
    category: CREATURE_CATEGORY.WATER,
    english_name: "Diplocaulus",
  },
  {
    name: CREATURE.OTTER,
    category: CREATURE_CATEGORY.SHOULDER_PETS,
    english_name: "Otter",
  },
  {
    name: CREATURE.RAVAGER,
    category: CREATURE_CATEGORY.CLIMBER,
    english_name: "Ravager",
  },
  {
    name: CREATURE.PYROMANE,
    category: CREATURE_CATEGORY.DAMAGE_DEALER,
    english_name: "Pyromane",
  },
  {
    name: CREATURE.MANAGARMR,
    category: CREATURE_CATEGORY.DAMAGE_DEALER,
    english_name: "Managarmr",
  },
  {
    name: CREATURE.CARBONEMYS,
    category: CREATURE_CATEGORY.SOAKER,
    english_name: "Carbonemys",
  },
  {
    name: CREATURE.ASTROCETUS,
    category: CREATURE_CATEGORY.FLYER,
    english_name: "Astrocetus",
  },
  {
    name: CREATURE.PROCOPTODON,
    category: CREATURE_CATEGORY.TAMING_BREEDING,
    english_name: "Procoptodon",
  },
  {
    name: CREATURE.MAEWING,
    category: CREATURE_CATEGORY.TAMING_BREEDING,
    english_name: "Maewing",
  },
  {
    name: CREATURE.DINOPITHECUS,
    category: CREATURE_CATEGORY.CLIMBER,
    english_name: "Dinopithecus",
  },
  {
    name: CREATURE.KENTROSAURUS,
    category: CREATURE_CATEGORY.MISC,
    english_name: "Kentrosaurus",
  },
  {
    name: CREATURE.REAPER_QUEEN,
    category: "Variant",
    english_name: "Reaper Queen",
  },
  {
    name: CREATURE.COMPY,
    category: CREATURE_CATEGORY.SHOULDER_PETS,
    english_name: "Compy",
  },
  {
    name: CREATURE.DIRE_BEAR,
    category: CREATURE_CATEGORY.DAMAGE_DEALER,
    english_name: "Dire Bear",
  },
  {
    name: CREATURE.MAGMASAUR,
    category: CREATURE_CATEGORY.FARMER,
    english_name: "Magmasaur",
  },
  {
    name: CREATURE.RHYNIOGNATHA,
    category: CREATURE_CATEGORY.SOAKER,
    english_name: "Rhyniognatha",
  },
  {
    name: CREATURE.MOSCHOPS,
    category: CREATURE_CATEGORY.FARMER,
    english_name: "Moschops",
  },
  {
    name: CREATURE.PEGOMASTAX,
    category: CREATURE_CATEGORY.SHOULDER_PETS,
    english_name: "Pegomastax",
  },
  {
    name: CREATURE.DILOPHOSAUR,
    category: CREATURE_CATEGORY.MISC,
    english_name: "Dilophosaur",
  },
  {
    name: CREATURE.TERROR_BIRD,
    category: CREATURE_CATEGORY.MISC,
    english_name: "Terror Bird",
  },
  {
    name: CREATURE.MICRORAPTOR,
    category: CREATURE_CATEGORY.SHOULDER_PETS,
    english_name: "Microraptor",
  },
  {
    name: CREATURE.DOEDICURUS,
    category: CREATURE_CATEGORY.FARMER,
    english_name: "Doedicurus",
  },
  {
    name: CREATURE.SNOW_OWL,
    category: CREATURE_CATEGORY.HEALER,
    english_name: "Snow Owl",
  },
  {
    name: CREATURE.SABERTOOTH_SALMON,
    category: CREATURE_CATEGORY.WATER,
    english_name: "Sabertooth Salmon",
  },
  {
    name: CREATURE.GIGANTORAPTOR,
    category: CREATURE_CATEGORY.DAMAGE_DEALER,
    english_name: "Gigantoraptor",
  },
  {
    name: CREATURE.YETI,
    category: CREATURE_CATEGORY.MISC,
    english_name: "Yeti",
  },
  {
    name: CREATURE.OASISAUR,
    category: CREATURE_CATEGORY.SOAKER,
    english_name: "Oasisaur",
  },
  {
    name: CREATURE.MEGALOSAURUS,
    category: CREATURE_CATEGORY.DAMAGE_DEALER,
    english_name: "Megalosaurus",
  },
  {
    name: CREATURE.LEEDSICHTHYS,
    category: CREATURE_CATEGORY.WATER,
    english_name: "Leedsichthys",
  },
  {
    name: CREATURE.MEGALODON,
    category: CREATURE_CATEGORY.DAMAGE_DEALER,
    english_name: "Megalodon",
  },
  {
    name: CREATURE.AMARGASAURUS,
    category: CREATURE_CATEGORY.SUPPORTER,
    english_name: "Amargasaurus",
  },
  {
    name: CREATURE.VOIDWYRM,
    category: CREATURE_CATEGORY.DAMAGE_DEALER,
    english_name: "Voidwyrm",
  },
  {
    name: CREATURE.ANGLERFISH,
    category: CREATURE_CATEGORY.FARMER,
    english_name: "Anglerfish",
  },
  {
    name: CREATURE.DIPLODOCUS,
    category: CREATURE_CATEGORY.MISC,
    english_name: "Diplodocus",
  },
  {
    name: CREATURE.PHIOMIA,
    category: CREATURE_CATEGORY.FARMER,
    english_name: "Phiomia",
  },
  {
    name: CREATURE.ANKYLOSAURUS,
    category: CREATURE_CATEGORY.FARMER,
    english_name: "Ankylosaurus",
  },
  {
    name: CREATURE.PACHYRHINOSAURUS,
    category: CREATURE_CATEGORY.SOAKER,
    english_name: "Pachyrhinosaurus",
  },
  {
    name: CREATURE.ENFORCER,
    category: CREATURE_CATEGORY.CLIMBER,
    english_name: "Enforcer",
  },
  {
    name: CREATURE.SHINEHORN,
    category: CREATURE_CATEGORY.SHOULDER_PETS,
    english_name: "Shinehorn",
  },
  {
    name: CREATURE.ICHTHYORNIS,
    category: CREATURE_CATEGORY.SHOULDER_PETS,
    english_name: "Ichthyornis",
  },
  {
    name: CREATURE.SHADOWMANE,
    category: CREATURE_CATEGORY.DAMAGE_DEALER,
    english_name: "Shadowmane",
  },
  {
    name: CREATURE.DEINONYCHUS,
    category: CREATURE_CATEGORY.MISC,
    english_name: "Deinonychus",
  },
  {
    name: CREATURE.PURLOVIA,
    category: CREATURE_CATEGORY.SUPPORTER,
    english_name: "Purlovia",
  },
  {
    name: CREATURE.VELONASAUR,
    category: CREATURE_CATEGORY.DAMAGE_DEALER,
    english_name: "Velonasaur",
  },
  {
    name: CREATURE.BARYONYX,
    category: CREATURE_CATEGORY.DAMAGE_DEALER,
    english_name: "Baryonyx",
  },
  {
    name: CREATURE.THYLACOLEO,
    category: CREATURE_CATEGORY.DAMAGE_DEALER,
    english_name: "Thylacoleo",
  },
  {
    name: CREATURE.QUETZAL,
    category: CREATURE_CATEGORY.FLYER,
    english_name: "Quetzal",
  },
  {
    name: CREATURE.DIREWOLF,
    category: CREATURE_CATEGORY.DAMAGE_DEALER,
    english_name: "Direwolf",
  },
  {
    name: CREATURE.PARASAUR,
    category: CREATURE_CATEGORY.SUPPORTER,
    english_name: "Parasaur",
  },
  {
    name: CREATURE.MAMMOTH,
    category: CREATURE_CATEGORY.SUPPORTER,
    english_name: "Mammoth",
  },
  {
    name: CREATURE.ROLL_RAT,
    category: CREATURE_CATEGORY.FARMER,
    english_name: "Roll Rat",
  },
  {
    name: CREATURE.RAPTOR,
    category: CREATURE_CATEGORY.MISC,
    english_name: "Raptor",
  },
  {
    name: CREATURE.MESOPITHECUS,
    category: CREATURE_CATEGORY.SHOULDER_PETS,
    english_name: "Mesopithecus",
  },
  {
    name: CREATURE.ACHATINA,
    category: CREATURE_CATEGORY.FARMER,
    english_name: "Achatina",
  },
  {
    name: CREATURE.TROODON,
    category: CREATURE_CATEGORY.MISC,
    english_name: "Troodon",
  },
  {
    name: CREATURE.ANDREWSARCHUS,
    category: CREATURE_CATEGORY.MISC,
    english_name: "Andrewsarchus",
  },
  {
    name: CREATURE.GIGANOTOSAURUS,
    category: CREATURE_CATEGORY.DAMAGE_DEALER,
    english_name: "Giganotosaurus",
  },
  {
    name: CREATURE.GACHA,
    category: CREATURE_CATEGORY.FARMER,
    english_name: "Gacha",
  },
  {
    name: CREATURE.SPINO,
    category: CREATURE_CATEGORY.DAMAGE_DEALER,
    english_name: "Spino",
  },
  {
    name: CREATURE.DAEODON,
    category: CREATURE_CATEGORY.HEALER,
    english_name: "Daeodon",
  },
  {
    name: CREATURE.TROPEOGNATHUS,
    category: CREATURE_CATEGORY.FLYER,
    english_name: "Tropeognathus",
  },
  {
    name: CREATURE.ONYC,
    category: CREATURE_CATEGORY.FLYER,
    english_name: "Onyc",
  },
  {
    name: CREATURE.CARNOTAURUS,
    category: CREATURE_CATEGORY.DAMAGE_DEALER,
    english_name: "Carnotaurus",
  },
  {
    name: CREATURE.SINOMACROPS,
    category: CREATURE_CATEGORY.SHOULDER_PETS,
    english_name: "Sinomacrops",
  },
  {
    name: CREATURE.PACHY,
    category: CREATURE_CATEGORY.MISC,
    english_name: "Pachy",
  },
  {
    name: CREATURE.CNIDARIA,
    category: CREATURE_CATEGORY.WATER,
    english_name: "Cnidaria",
  },
  {
    name: CREATURE.ALLOSAURUS,
    category: CREATURE_CATEGORY.DAMAGE_DEALER,
    english_name: "Allosaurus",
  },
  {
    name: CREATURE.FEATHERLIGHT,
    category: CREATURE_CATEGORY.SHOULDER_PETS,
    english_name: "Featherlight",
  },
  {
    name: CREATURE.GIANT_QUEEN_BEE,
    category: CREATURE_CATEGORY.FARMER,
    english_name: "Giant Queen Bee",
  },
  {
    name: CREATURE.MEGACHELON,
    category: CREATURE_CATEGORY.SOAKER,
    english_name: "Megachelon",
  },
  {
    name: CREATURE.TAPEJARA,
    category: CREATURE_CATEGORY.FLYER,
    english_name: "Tapejara",
  },
  {
    name: CREATURE.YUTYRANNUS,
    category: CREATURE_CATEGORY.SUPPORTER,
    english_name: "Yutyrannus",
  },
  {
    name: CREATURE.GASBAGS,
    category: CREATURE_CATEGORY.SOAKER,
    english_name: "Gasbags",
  },
  {
    name: CREATURE.LYSTROSAURUS,
    category: CREATURE_CATEGORY.SUPPORTER,
    english_name: "Lystrosaurus",
  },
  {
    name: CREATURE.ARANEO,
    category: CREATURE_CATEGORY.MISC,
    english_name: "Araneo",
  },
  {
    name: CREATURE.BASILOSAURUS,
    category: CREATURE_CATEGORY.SOAKER,
    english_name: "Basilosaurus",
  },
  {
    name: CREATURE.ASTRODELPHIS,
    category: CREATURE_CATEGORY.DAMAGE_DEALER,
    english_name: "Astrodelphis",
  },
  {
    name: CREATURE.EQUUS,
    category: CREATURE_CATEGORY.TAMING_BREEDING,
    english_name: "Equus",
  },
  {
    name: CREATURE.THORNY_DRAGON,
    category: CREATURE_CATEGORY.MISC,
    english_name: "Thorny Dragon",
  },
  {
    name: CREATURE.TITANOBOA,
    category: CREATURE_CATEGORY.MISC,
    english_name: "Titanoboa",
  },
  {
    name: CREATURE.COELACANTH,
    category: CREATURE_CATEGORY.WATER,
    english_name: "Coelacanth",
  },
  {
    name: CREATURE.MEGANEURA,
    category: CREATURE_CATEGORY.MISC,
    english_name: "Meganeura",
  },
  {
    name: CREATURE.OVIRAPTOR,
    category: CREATURE_CATEGORY.FARMER,
    english_name: "Oviraptor",
  },
  {
    name: CREATURE.PELAGORNIS,
    category: CREATURE_CATEGORY.FLYER,
    english_name: "Pelagornis",
  },
  {
    name: CREATURE.KAPROSUCHUS,
    category: CREATURE_CATEGORY.WATER,
    english_name: "Kaprosuchus",
  },
  {
    name: CREATURE.THERIZINOSAUR,
    category: CREATURE_CATEGORY.DAMAGE_DEALER,
    english_name: "Therizinosaur",
  },
  {
    name: CREATURE.CARCHARODONTOSAURUS,
    category: CREATURE_CATEGORY.DAMAGE_DEALER,
    english_name: "Carcharodontosaurus",
  },
  {
    name: CREATURE.PULMONOSCORPIUS,
    category: CREATURE_CATEGORY.MISC,
    english_name: "Pulmonoscorpius",
  },
  {
    name: CREATURE.MEGATHERIUM,
    category: CREATURE_CATEGORY.DAMAGE_DEALER,
    english_name: "Megatherium",
  },
  {
    name: CREATURE.ARCHAEOPTERYX,
    category: CREATURE_CATEGORY.SHOULDER_PETS,
    english_name: "Archaeopteryx",
  },
  {
    name: CREATURE.DIMETRODON,
    category: CREATURE_CATEGORY.TAMING_BREEDING,
    english_name: "Dimetrodon",
  },
  {
    name: CREATURE.ARGENTAVIS,
    category: CREATURE_CATEGORY.FARMER,
    english_name: "Argentavis",
  },
  {
    name: CREATURE.CERATOSAURUS,
    category: CREATURE_CATEGORY.DAMAGE_DEALER,
    english_name: "Ceratosaurus",
  },
  {
    name: CREATURE.IGUANODON,
    category: CREATURE_CATEGORY.MISC,
    english_name: "Iguanodon",
  },
  {
    name: CREATURE.SARCO,
    category: CREATURE_CATEGORY.WATER,
    english_name: "Sarco",
  },
  {
    name: CREATURE.GRIFFIN,
    category: CREATURE_CATEGORY.FLYER,
    english_name: "Griffin",
  },
  {
    name: CREATURE.ELECTROPHORUS,
    category: CREATURE_CATEGORY.WATER,
    english_name: "Electrophorus",
  },
  {
    name: CREATURE.PLESIOSAUR,
    category: CREATURE_CATEGORY.WATER,
    english_name: "Plesiosaur",
  },
  {
    name: CREATURE.OVIS,
    category: CREATURE_CATEGORY.FARMER,
    english_name: "Ovis",
  },
  {
    name: CREATURE.MEGALOCEROS,
    category: CREATURE_CATEGORY.FARMER,
    english_name: "Megaloceros",
  },
  {
    name: CREATURE.TITANOSAUR,
    category: CREATURE_CATEGORY.SOAKER,
    english_name: "Titanosaur",
  },
  {
    name: CREATURE.BEELZEBUFO,
    category: CREATURE_CATEGORY.FARMER,
    english_name: "Beelzebufo",
  },
  {
    name: CREATURE.TUSOTEUTHIS,
    category: CREATURE_CATEGORY.DAMAGE_DEALER,
    english_name: "Tusoteuthis",
  },
  {
    name: CREATURE.MORELLATOPS,
    category: CREATURE_CATEGORY.MISC,
    english_name: "Morellatops",
  },
  {
    name: CREATURE.LYMANTRIA,
    category: CREATURE_CATEGORY.FLYER,
    english_name: "Lymantria",
  },
  {
    name: CREATURE.PHOENIX,
    category: CREATURE_CATEGORY.FLYER,
    english_name: "Phoenix",
  },
  {
    name: CREATURE.WYVERN,
    category: CREATURE_CATEGORY.DAMAGE_DEALER,
    english_name: "Wyvern",
  },
  {
    name: CREATURE.FJORDHAWK,
    category: CREATURE_CATEGORY.SHOULDER_PETS,
    english_name: "Fjordhawk",
  },
  {
    name: CREATURE.FENRIR,
    category: CREATURE_CATEGORY.DAMAGE_DEALER,
    english_name: "Fenrir",
  },
]);
